version: '3'
services:
  api:
    build: ./todoapi
    command: mix phx.server
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/tododb

  # web:
  #   build: ./todofront
  #   command: npm start
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - api

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=tododb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

