services:
  api:
    build: ./todoapi
    command: /bin/sh docker_dev_start.sh
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/tododb

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=tododb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  front:
    build: ./todofront
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  postgres_data:

